services:
  db:
    image: postgres:15-alpine
    container_name: go_pgsql_db
    restart: always
    environment:
      POSTGRES_DB: jwt_go_docker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: +}</4Mi1
    volumes:
      - pg_data:/var/lib/postgresql/data
    
    ports:
      - "5433:5432"

  migrate:
    image: migrate/migrate
    container_name: go_db_migrate
    volumes:
      - ./db/migrations:/migrations
    environment:
      PGPASSWORD: '+}</4Mi1'
    depends_on:
      - db
    command:
      - -path=/migrations
      - -database=postgres://postgres@db:5432/jwt_go_docker?sslmode=disable
      - up
    restart: on-failure

  app:
    build: .
    restart: always
    depends_on:
      - db
      - migrate
    ports:
      - "8080:8080"
    environment:
      DB_USER: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_PASSWORD: +}</4Mi1
      DB_NAME: jwt_go_docker
      JWT_SECRET: jjk_is_so_far_the_best
  
volumes:
  pg_data:
