version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: go_pgsql_db
    restart: always
    environment:
      POSTGRES_DB: jwt_go_docker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: +}</4Mi1
    volumes:
      - pg_data:/var/lib/postgresql/data

      - ./db/migrations:/docker-entrypoint-initdb.d
    
    ports:
      - "5433:5432"

  app:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_USER: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_PASSWORD: +}</4Mi1
      DB_NAME: jwt_go_docker
    


  
volumes:
  pg_data:
